# Generated by Django 6.1.1 on 2026-09-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning & Maintenance'), ('hardware', 'Hardware Upgrades'), ('software', 'Software & OS'), ('custom', 'Custom Builds')], default='cleaning', max_length=20)),
                ('delivery_type', models.CharField(choices=[('home_service', 'Home Service'), ('walk_in', 'Walk-in'), ('pickup_delivery', 'Pick-up & Delivery')], default='home_service', max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-tools', help_text='Bootstrap Icons class, e.g. bi-laptop', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for TBA pricing', max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('requires_customer_parts', models.BooleanField(default=False, help_text='Customer must provide parts or license')),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
